
local this = {}
this.crateData = {
	{name="Common Crate", Description="Common 70% | Rare 25% | Epic 5%", DotCost=500, RobuxCost=3, ImageId="rbxassetid://137470240215436", BackgroundColor=Color3.fromRGB(219,210,156), LootTable={{Rarity="Common",Chance=70},{Rarity="Rare",Chance=25},{Rarity="Epic",Chance=5}}},

	{name="Rare Crate", Description="Rare 65% | Epic 25% | Legendary 10%", DotCost=2000, RobuxCost=8, ImageId="rbxassetid://113766676258125", BackgroundColor=Color3.fromRGB(125,185,255), LootTable={{Rarity="Rare",Chance=65},{Rarity="Epic",Chance=25},{Rarity="Legendary",Chance=10}}},

	{name="Epic Crate", Description="Epic 70% | Legendary 25% | Mythic 5%", DotCost=8000, RobuxCost=15, ImageId="rbxassetid://76036925721310", BackgroundColor=Color3.fromRGB(190,120,255), LootTable={{Rarity="Epic",Chance=70},{Rarity="Legendary",Chance=25},{Rarity="Mythic",Chance=5}}},

	{name="Legendary Crate", Description="Legendary 75% | Mythic 20% | Divine 5%", DotCost=30000, RobuxCost=25, ImageId="rbxassetid://133812671517218", BackgroundColor=Color3.fromRGB(255,205,80), LootTable={{Rarity="Legendary",Chance=75},{Rarity="Mythic",Chance=20},{Rarity="Divine",Chance=5}}},

	{name="Neon Crate", Description="Rare 50% | Epic 35% | Legendary 15%", DotCost=100000, RobuxCost=35, ImageId="rbxassetid://84551668980990", BackgroundColor=Color3.fromRGB(50,255,220), LootTable={{Rarity="Rare",Chance=50},{Rarity="Epic",Chance=35},{Rarity="Legendary",Chance=15}}},

	{name="Galaxy Crate", Description="Epic 60% | Legendary 30% | Mythic 10%", DotCost=300000, RobuxCost=49, ImageId="rbxassetid://105937197834473", BackgroundColor=Color3.fromRGB(90,70,170), LootTable={{Rarity="Epic",Chance=60},{Rarity="Legendary",Chance=30},{Rarity="Mythic",Chance=10}}},

	{name="Lava Crate", Description="Epic 55% | Legendary 35% | Mythic 10%", DotCost=800000, RobuxCost=59, ImageId="rbxassetid://96429930986370", BackgroundColor=Color3.fromRGB(255,90,40), LootTable={{Rarity="Epic",Chance=55},{Rarity="Legendary",Chance=35},{Rarity="Mythic",Chance=10}}},

	{name="Cyber Crate", Description="Legendary 70% | Mythic 25% | Divine 5%", DotCost=2000000, RobuxCost=69, ImageId="rbxassetid://119015447627616", BackgroundColor=Color3.fromRGB(0,220,255), LootTable={{Rarity="Legendary",Chance=70},{Rarity="Mythic",Chance=25},{Rarity="Divine",Chance=5}}},

	{name="Divine Crate", Description="Mythic 80% | Divine 18% | Secret 2%", DotCost=5000000, RobuxCost=79, ImageId="rbxassetid://140287819005458", BackgroundColor=Color3.fromRGB(255,255,180), LootTable={{Rarity="Mythic",Chance=80},{Rarity="Divine",Chance=18},{Rarity="Secret",Chance=2}}},

	{name="Void Crate", Description="Divine 80% | Secret 19% | Impossible 1%", DotCost=10000000, RobuxCost=99, ImageId="rbxassetid://83192048105535", BackgroundColor=Color3.fromRGB(128,128,128), LootTable={{Rarity="Divine",Chance=80},{Rarity="Secret",Chance=19},{Rarity="Impossible",Chance=1}}},
}
return this
